src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\ImageRepository;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=ImageRepository::class)
 */
class Image
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $path;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $alt;

    /**
     * @Assert\Image(
     *  mimeTypes= {"image/jpeg", "image/jpg", "image/png"},
     *  mimeTypesMessage = "Le fichier ne possède pas une extension valide ! Veuillez insérer une image en .jpg, .jpeg ou .png",
     *  maxSize = "900k",
     *  maxSizeMessage = "Le fichier est trop grand. Taille max 900k",
     *  minWidth = 500,
     *  minWidthMessage = "La largeur de cette image est trop petite",
     *  maxWidth = 3000,
     *  maxWidthMessage = "La largeur de cette image est trop grande",
     *  minHeight = 282,
     *  minHeightMessage = "La hauteur de cette image est trop petite",
     *  maxHeight = 1687,
     *  maxHeightMessage ="La hauteur de cette image est trop grande",
     *  )
     */
    private $file;


    /**
     * @ORM\ManyToOne(targetEntity=Trick::class, inversedBy="images")    
     * @ORM\JoinColumn(nullable=true)
     */
    private $trick;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function getPathCropped(): ?string
    {
        return $this->path . '/cropped';
    }

    public function getPathThumbnail(): ?string
    {
        return $this->path . '/thumbnail';
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(?string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }

    public function setFile(UploadedFile $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getTrick(): ?Trick
    {
        return $this->trick;
    }

    public function setTrick(?Trick $trick): self
    {
        $this->trick = $trick;

        return $this;
    }
}

src/Entity/Trick.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\TrickRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrickRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Un trick possède déjà ce nom, merci de le modifier"
 * )
 * @UniqueEntity(
 *  fields={"slug"},
 *  message="Un trick possède déjà ce slug"
 * )
 */
class Trick
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3, max=255, minMessage="Le titre doit avoir minimum 3 caratères !")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=10, minMessage="La description doit avoir minimum 10 caratères !")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="tricks")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="trick",orphanRemoval=true, cascade={"persist", "remove"})
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="trick", orphanRemoval=true, cascade={"persist", "remove"})
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=Video::class, mappedBy="trick",orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $videos;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;



    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    //...

    /* public function __toString()
    {
        return $this->title;
    } */

    // ...
    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Initialisation du slug avant un persist ou un update
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setTrick($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getTrick() === $this) {
                $image->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /* public function getMainImage(): ?Image
    {
        return $this->mainImage;
    }

    public function setMainImage(Image $mainImage): self
    {
        $this->mainImage = $mainImage;

        return $this;
    } */
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Trick;
use App\Form\ImageType;
use App\Form\VideoType;
use App\Entity\Category;
use App\Form\CategoryType;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class TrickType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, $this->getOptions('Nom', 'Nom du trick'))
            ->add('description', TextareaType::class, $this->getOptions('Description', 'Description du trick'))
            ->add('category', EntityType::class, $this->getOptions('Catégorie', 'Catégorie du trick', [
                'class' => Category::class,
                'choice_label' => 'title',
            ]))
            ->add('images', CollectionType::class, [
                'entry_type' => ImageType::class,
                'allow_add' => true,
                'allow_delete' => true
            ])
            ->add('videos', CollectionType::class, [
                'entry_type' => VideoType::class,
                'allow_add' => true,
                'allow_delete' => true
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {

        $resolver->setDefaults([
            'data_class' => Trick::class
        ]);
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Trick;
use App\Entity\Comment;
use App\Form\TrickType;
use App\Form\CommentType;
use App\Service\Cropper16x9;
use App\Service\UploadImage;
use App\Service\ThumbnailResizer;
use App\Repository\TrickRepository;
use Doctrine\Persistence\ObjectManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TrickController extends AbstractController
{
    /**
     *
     * @Route("/trick/new", name="trick_create")
     * @Route("/trick/edit/{slug}", name="trick_edit")
     * @IsGranted("ROLE_USER") 
     */
    public function form(Trick $trick = null, Request $request, EntityManagerInterface $manager, Cropper16x9 $cropper16x9, UploadImage $uploadImage, ThumbnailResizer $thumbnailResizer) //"Doctrine\Persistence\ObjectManager" but no such service exists.
    {
        if (!$trick) {
            $trick = new Trick();
        }

        $form = $this->createForm(TrickType::class, $trick);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (!$trick->getSlug()) {
                $trick->setCreatedAt(new \DateTime());
            }
            foreach ($trick->getImages() as $image) {
                // Assignation du trick à l'image
                $image->setTrick($trick);
                // Enregistrement de l'image sur le disque dur et en BDD
                $image = $uploadImage->saveImage($image);
                // On persiste l'entité Image une fois bien remplie dans la BDD
                $manager->persist($image);

                // Enregistrement sur le disque de l'image redimensionnée en 16x9
                $cropper16x9->crop($image);
                // Enregistrement sur le disque de l'image redimensionnée à la taille d'un thumbnail (!!! A partir de l'image 16x9 !!!)
                $thumbnailResizer->resize($image);
            }

            foreach ($trick->getVideos() as $video) {
                $video->setTrick($trick);
                $manager->persist($video);
            }

            $trick->setCreatedAt(new \DateTime());
            $trick->setUpdatedAt(new \DateTime());
            $trick->setUser($this->getUser());

            $manager->persist($trick);
            $manager->flush();

            $this->addFlash(
                'success',
                'Le trick <strong>' . $trick->getTitle() . '</strong> a bien été enregistré !'
            );

            return $this->redirectToRoute('home', ['_fragment' => 'portfolio']);
        }

        return $this->render('trick/create.html.twig', [
            'form' => $form->createView(),
            'editMode' => $trick->getSlug() !== null
        ]);
    }



    /**
     * @Route("/trick/show/{slug}", name="trick_show")
     */
    public function show(TrickRepository $repo, Request $request, EntityManagerInterface $manager, $slug)
    {
        $trick = $repo->findOneBySlug($slug);

        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setCreatedAt(new \DateTime());
            $comment->setTrick($trick);
            $comment->setUser($this->getUser());

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash(
                'success',
                'Votre commentaire a bien été enregistré !'
            );

            return $this->redirectToRoute('trick_show', ['slug' => $trick->getSlug()]);
        }
        return $this->render('trick/show.html.twig', [
            'trick' => $trick,
            'form' => $form->createView()
        ]);
    }

    /**
     * Get the 10 next comments in the database and create a Twig file with them that will be displayed via Javascript
     * 
     * @Route("/trick/{slug}/{start}", name="loadMoreComments", requirements={"start": "\d+"})
     */
    public function loadMoreComments(TrickRepository $repo, $slug, $start = 10)
    {
        $trick = $repo->findOneBySlug($slug);

        return $this->render('trick/loadMoreComments.html.twig', [
            'trick' => $trick,
            'start' => $start
        ]);
    }



    /**
     * @Route("/trick/delete/{slug}", name="trick_delete")
     * @IsGranted("ROLE_USER")
     */
    public function delete(TrickRepository $repo, EntityManagerInterface $manager, $slug)
    {
        $trick = $repo->findOneBySlug($slug);

        $fileSystem = new Filesystem();

        foreach ($trick->getImages() as $image) {
            $fileSystem->remove($image->getPath() . '/' . $image->getTitle());
            $fileSystem->remove($image->getPath() . '/cropped/' . $image->getTitle());
            $fileSystem->remove($image->getPath() . '/thumbnail/' . $image->getTitle());
        }

        $manager->remove($trick);
        $manager->flush();

        $this->addflash(
            'success',
            "Le trick <strong>{$trick->getTitle()}</strong> a été supprimé avec succès !"
        );

        return $this->redirectToRoute('home');
    }
}

templates/trick/home.html.twig
{% extends 'base.html.twig'%}

{% block body %}
	<!-- Masthead-->
	<header class="masthead">
		<div class="container">
			<div class="masthead-subheading">SnowTricks</div>
			<div class="masthead-heading text-uppercase">SnowTricks</div>
			<a class="" href="#portfolio">
				<i class="bi bi-mouse fa-4x"></i>
			</a>
		</div>
	</header>


	<h1 class="text-center mt-5"> {{ title }}</h1>


	<!-- Présentation -->
	<section class="page-section" id="about">
		<div class="container">
			<div class="row free text-center text-lg-start">
				<div class="col-lg-6 side-left">
					<img src="img/snowboard.jpg" alt="">
				</div>
				<div class="col-lg-6 side-right">
					<h2 class="section-heading text-uppercase">SnowTricks</h2>
					<h3 class="section-subheading text-muted">Histoire du snowboard</h3>
					<p class="text-muted">Les origines du snowboard sont difficiles à déterminer avec certitude. On peut en retrouver les prémices dans les années 1920. Dès cette époque, il semble que, indépendamment de toute invention ou commercialisation, de nombreuses personnes se soient amusées à glisser sur la neige debout sur une planche. C'est beaucoup plus tard qu'auront lieu les premiers dépôts de brevets et les batailles juridiques qui permettent aujourd'hui à Jake Burton d'affirmer qu'il est l'inventeur du snowboard. Pourtant de nombreuses personnes revendiquent, à tort ou à raison, un rôle déterminant dans sa création, ou même sa paternité. Et s'ils sont en effet nombreux à avoir joué un rôle dans l'histoire de ce nouveau sport de glisse, il est difficile de mesurer l'importance de l'apport de chacun. En outre de nombreux pionniers ont développé des innovations identiques chacun de leurs côtés.</p>
				</div>
			</div>
		</div>
	</section>


	<!-- Tricks listing -->
	<!-- Portfolio / Programmation Grid-->
	<section class="page-section bg-lightx" id="portfolio">
		<div class="container ">
			<div class="text-center">
				<h2 class="section-heading-programmation text-uppercase">Les tricks</h2>
			</div>
			<div class="row" id="trickList">
				{% for trick in tricks %}
					<div class="col-lg-3 col-sm-6 mb-4 mb-lg-4">
						<div class="portfolio-item">
							<a class="portfolio-link" href="{{ path('trick_show', {'slug': trick.slug}) }}">
								<div class="portfolio-hover">
									<div class="portfolio-hover-content text-center">
										<i class="fas fa-ellipsis-h fa-3x"></i>
										<br/></div>
								</div>
								{% if trick.images|length > 0  %}
									<img src="{{ asset(trick.images[0].pathThumbnail ~ '/' ~ trick.images[0].title) }}" class="card-img-top" alt="{{ trick.images[0].alt }}">
								{% endif %}
							</a>
							<div class="portfolio-caption ">
								<div class="portfolio-caption-heading text-uppercase mb-4">{{ trick.title }}</div>

								<hr class="my-4 mx-auto text-muted"/>
								<div class="d-flex justify-content-between">
									<h6 class="portfolio-caption-subheading text-muted text-md-start col-md-8">{{ trick.category.title }}</h6>
									{% if app.user %}
										<div class="operations">
											<a href="{{ path('trick_edit', {'slug': trick.slug}) }}">
												<i class="fas fa-pencil-alt"></i>
											</a>
											<a href="{{ path('trick_delete', {'slug': trick.slug}) }}" onclick="return confirm(`Êtes-vous sûr de vouloir supprimer le trick : {{trick.title}} ?`)">
												<i class="fas fa-trash-alt"></i>
											</a>
										</div>
									{% endif %}
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
			<div class="row">
				<div class="col-12 text-center">
					<button id="loadMoreTricks" class="btn btn-primary">Voir plus de tricks</button>
				</div>
			</div>
			<a href="#tricks">
				<i id="arrow-up" class="fas fa-arrow-up fa-3x float-right"></i>
			</a>
		</div>
	</section>
{% endblock %}
{% block javascripts %} {{ parent() }}<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
	<script>
		$("#arrow-up").hide();
click = 0;
function loadMoreTricks(event) {
event.preventDefault();
click ++;
var start = 10 * click;
const url = "{{ path('loadMoreTricks') }}" + start;

axios.get(url).then(function (response) {
console.log(response);
$("#trickList").append(response.data);
$("#arrow-up").show();
}).catch(function (error) {
if (response.status === 403) {
window.alert("Vous n'êtes pas autorisé à effectuer cette action !");
} else if (response.status === 404) {
window.alert("La page appelé n'existe pas");
} else {
window.alert("Une erreur est survenue !");
}
});
}

document.getElementById("loadMoreTricks").addEventListener("click", loadMoreTricks);
	</script>


{% endblock %}

templates/trick/loadMoreComments.html.twig
{% for comment in trick.comments | slice(start, start + 10) %}
	<div class="comment row mx-auto">
		<div class="col-md-10 col-12 mx-auto row">
			<div class="userImage col-lg-2 col-4">
				<img src="{{ asset(comment.user.imagePath ~ '/' ~ comment.user.imageName) }}" class="avatar avatar-medium" alt="comment.user.username">
			</div>
			<p class="col-lg-10 col-8 bg-light">
				<strong>{{ trick.user.firstName }} {{ trick.user.lastName }}</strong>
				<small class="text-muted">({{ comment.createdAt | date('d/m/Y à H:i') }}) :</small>
				<br>{{ comment.content }}
			</p>
		</div>
	</div>
{% endfor %}

templates/trick/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SnowTricks - {{ trick.title }}
{% endblock %}

{% block body %}
	<div
		id="trickMainImage" class="position-relative border border-dark">
		{# <img class="w-100" src="{{ asset(trick.mainImage.pathCropped ~ '/' ~ trick.mainImage.title) }}" alt="{{ trick.mainImage.alt }}"> #}
		{% if trick.images|length > 0  %}
			<img class="w-100" src="{{ asset(trick.images[0].pathThumbnail ~ '/' ~ trick.images[0].title) }}" class="card-img-top" alt="{{ trick.images[0].alt }}">
		{% endif %}
		<div id="trickTitle" class="text-center">
			<h1>{{ trick.title }}</h1>
		</div>
		{% if app.user %}
			<div class="operations">
				<a href="{{ path('trick_edit', {'slug': trick.slug}) }}">
					<i class="fas fa-pencil-alt"></i>
				</a>
				<a href="{{ path('trick_delete', {'slug': trick.slug}) }}" onclick="return confirm(`Êtes-vous sûr de vouloir supprimer le trick : {{trick.title}} ?`)">
					<i class="fas fa-trash-alt"></i>
				</a>
			</div>
		{% endif %}
	</div>

	<div class="row" id="trickMedia">
		{% for image in trick.images %}
			<div class="trickImage mx-auto col-sm-6 col-md-4 col-lg-4 col-xl-3 border border-dark">
				<img src="{{ asset(image.pathThumbnail ~ '/' ~ image.title) }}" width="100%" alt="{{ image.alt }}">
			</div>
		{% endfor %}
		{% for video in trick.videos %}
			<div class="trickVideo col-sm-6 col-md-4 col-lg-4 col-xl-3 border border-dark">
				{% if video.url is not empty %}
					{% set id = video.url|split('v=')|last %}
					{% set id1 = id|split('&')|first %}
					{% set id2 = id1|split('/')|last %}
					<figure style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; margin: 0px;">
						<iframe width="100%" height="315" src="https://www.youtube.com/embed/{{id2}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
					</figure>
				{% endif %}
			</div>
		{% endfor %}
	</div>

	<div class="row text-center" id="seeMedia">
		<button class="btn btn-info col-10 mt-3">Voir les médias</button>
	</div>

	<div class="row">
		<div id="trickDescription" class="col-11 mx-auto mt-4 mb-1 bg-light">
			<h3>Description :</h3> {{ trick.description | raw }}
		</div>
	</div>

	<div class="row">
		<div class="row text-center col-11 mx-auto my-2 bg-light" id="infos">
			<p class="col">Publié le {{ trick.createdAt | date('d/m/Y') }}
				à {{ trick.createdAt | date('H:i') }}
				par {{ trick.user.firstName }} {{ trick.user.lastName }}</p>
			<p class="col">Mis à jour le {{ trick.updatedAt | date('d/m/Y') }}
				à {{ trick.updatedAt | date('H:i') }}</p>
			<p class="col">Catégorie : {{ trick.category.title }}</p>
		</div>
	</div>

	<hr>

	<div class="row text-center">
		{% if app.user %}
			<div class="col-sm-10 col-md-8 mx-auto"> {{ form_start(form) }} {{ form_widget(form) }}
				<button type="submit" class="btn btn-success col-sm-s8 mx-auto">Ajouter</button> {{ form_end(form) }}
			</div>
		{% else %}
			<div class="col-sm-10 col-md-8 mx-auto">
				<h6>Veuillez vous
					<a href="{{ path('account_login') }}" class="text-dark">connecter</a>
					pour laisser un commentaire</h6>
			</div>
		{% endif %}
	</div>

	<hr>

	<section id="comments">
		{% for comment in trick.comments | slice(0,10) %}
			<div class="comment row mx-auto">
				<div class="col-md-10 col-12 mx-auto row">
					<div class="userImage col-lg-2 col-4">
						<img src="{{ asset(comment.user.imagePath ~ '/' ~ comment.user.imageName) }}" class="avatar avatar-medium" alt="comment.user.username">
					</div>
					<p class="col-lg-10 col-8 bg-light">
						<strong>{{ trick.user.firstName }} {{ trick.user.lastName }}</strong>
						<small class="text-muted">({{ comment.createdAt | date('d/m/Y à H:i') }}) :</small>
						<br>{{ comment.content }}
					</p>
				</div>
			</div>
		{% endfor %}
	</section>
	<div class="row text-center">
		<button id="loadMoreComments" class="btn btn-primary col-md-6 col-8 mx-auto mb-5">Voir plus de commentaires</button>
	</div>

	<!-- The Modal/Lightbox -->
	<div id="imageModal" class="modal">
		<span class="close cursor">
			<i class="fas fa-times fa-2x"></i>
		</span>
		<img src="#" alt="">
	</div>
{% endblock %}
{% block javascripts %} {{ parent() }}
	<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
	<script>
		click = 0;
function loadMoreComments(event) {
event.preventDefault();
click ++;
var start = 10 * click;
const url = "{{ path('loadMoreComments', {'slug': trick.slug} ) }}/" + start;

axios.get(url).then(function (response) {
$("#comments").append(response.data);
}).catch(function (error) {
if (response.status === 403) {
window.alert("Vous n'êtes pas autorisé à effectuer cette action !");
} else if (response.status === 404) {
window.alert("La page appelé n'existe pas");
} else {
window.alert("Une erreur est survenue !");
}
});
}

document.getElementById("loadMoreComments").addEventListener("click", loadMoreComments);
	</script>
	<script>
		$(".trickImage img").click(function () {
var originalSrc = this.src.replace("thumbnail/", "");
$(".modal img").attr("src", originalSrc);
$(".modal img").attr("alt", this.alt);
$("#imageModal").show();
});

$(".close.cursor").click(function () {
$("#imageModal").hide();
});

$("#seeMedia").click(function () {
$("#trickMedia").show();
$("#seeMedia").hide();
});
	</script>
{% endblock %}